name: sass_builder
description: Sass builder with `package:build`.
version: 0.1.0
author: ntaoo <ntaoo.g@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  build: ^0.4.0
  path: ^1.0.0
dev_dependencies:
  test: ^0.12.0